# Auto-generated - DO NOT EDIT
# mypy: disable-error-code="misc"
# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from typing import Any, Literal, TypeAlias, TypedDict

from typing_extensions import NotRequired


class AddUrlToTaskRequest(TypedDict):
    title: NotRequired[str]
    url: str


class AllowedContentTypeItem(TypedDict):
    name: str
    url: str


class ArticleAuthorResponse(TypedDict):
    name: str | None


class AssetContent(TypedDict):
    type: Literal["url", "api_url", "html_body"]
    value: str


class Choice(TypedDict):
    id: str
    name: str


AssetFieldTypes: TypeAlias = Literal[
    "checkbox",
    "currency_number",
    "date",
    "dropdown",
    "label",
    "radio_button",
    "text_area",
    "percentage_number",
    "rich_text",
    "simple_number",
    "text",
]


class Links(TypedDict):
    asset: str
    asset_fields: str


class AssetFieldUpdateResponse(TypedDict):
    id: str
    links: Links
    name: str
    type: AssetFieldTypes
    values: list[str]


class AssetLineageCreateRequest(TypedDict):
    icon_url: NotRequired[str]
    name: str
    rendition_id: NotRequired[str]
    uri: str


class Links1(TypedDict):
    asset: str
    self: str


class AssetLineageResponse(TypedDict):
    asset_id: str
    created_at: str
    icon_url: str | None
    id: str
    links: Links1
    name: str
    rendition_id: str | None
    uri: str
    used_in: Literal["external"]
    version_id: str


class Permission(TypedDict):
    access_type: Literal["view", "edit"]
    id: str
    is_owner: NotRequired[bool]


class AssetPermissionBulkCreateRequest(TypedDict):
    permissions: list[Permission]
    type: Literal["user", "team"]


class AssetPermissionUpdateRequest(TypedDict):
    access_type: NotRequired[Literal["view", "edit"]]
    is_owner: NotRequired[bool]


class Links2(TypedDict):
    self: str


class Value(TypedDict):
    key: str
    title: str


class AssetVersionCreateRequest(TypedDict):
    key: str
    title: str


class AttachmentRequest(TypedDict):
    key: str
    name: str


class AttachmentResponse(TypedDict):
    id: str
    name: str
    url: str


class BaseAssetField(TypedDict):
    id: str
    name: str
    type: str
    values: list[str]


class BaseAssetRenditionResponse(TypedDict):
    created_at: str
    id: str
    mime_type: str
    name: str
    url: str


class Links3(TypedDict):
    self: NotRequired[str]
    versions: NotRequired[str]


class BaseContentTypeModel(TypedDict):
    component: bool
    content_type_guid: str
    created_at: str
    created_by: str
    description: NotRequired[str]
    disabled: NotRequired[bool]
    links: Links3
    name: str
    source: NotRequired[str]
    source_id: NotRequired[str]
    source_metadata: NotRequired[str]
    thumbnail_guid: NotRequired[str]
    updated_at: str
    updated_by: str


class Links4(TypedDict):
    content_type: NotRequired[str]
    self: NotRequired[str]


class BaseContentTypeVersionModel(TypedDict):
    created_at: str
    created_by: str
    expected_locales: list[str]
    latest: bool
    links: Links4
    version_guid: str


BaseFieldDefinitionType: TypeAlias = Literal["boolean", "json", "url", "location"]


class BaseFormFieldRequest(TypedDict):
    identifier: str
    type: str
    values: list[Any]


class BaseFormFieldResponse(TypedDict):
    identifier: str
    is_protected: NotRequired[bool]
    type: str
    values: list[Any]


class BaseObjectFieldUpdatePayload(TypedDict):
    type: str
    values: list[Any]


class Links5(TypedDict):
    accessor: str | None


class BasePermissionsResponseSchema(TypedDict):
    access_type: Literal["view", "edit", "comment", "delete"]
    id: str
    is_owner: bool
    links: Links5
    name: str
    type: Literal["user", "team", "organization"]


class BaseSettingsFieldCreatePayload(TypedDict):
    helper_text: NotRequired[str]
    is_active: bool
    name: str
    type: str


class BaseSettingsFieldUpdatePayload(TypedDict):
    helper_text: NotRequired[str]
    is_active: NotRequired[bool]
    name: NotRequired[str]
    type: str


class Links6(TypedDict):
    source: str


class BaseSettingsFieldsResponse(TypedDict):
    helper_text: str
    id: str
    is_active: bool
    links: Links6
    name: str
    type: str


class BaseTemplateFormField(TypedDict):
    helper_text: str | None
    identifier: str
    is_protected: NotRequired[bool]
    is_readonly: bool
    is_required: bool
    label: str | None
    sort_order: int
    type: Literal[
        "brief",
        "checkbox",
        "currency_number",
        "date",
        "dropdown",
        "file",
        "instruction",
        "label",
        "percentage_number",
        "radio_button",
        "richtext",
        "section",
        "simple_number",
        "text",
        "text_area",
    ]


class BaseTemplateResponse(TypedDict):
    applicable_to: list[Literal["work_request", "task_brief", "campaign_brief"]]
    description: str
    id: str
    is_active: bool
    title: str


class BatchFileUrlResponse(TypedDict):
    urls: dict[str, str | None]


class BooleanFieldValueModel(TypedDict):
    bool_value: bool
    order_index: NotRequired[int]


class Criterion(TypedDict):
    description: NotRequired[str]
    id: str
    name: NotRequired[str]


class BrandComplianceCategoriesResponse(TypedDict):
    criteria: list[Criterion]
    id: str
    name: NotRequired[str]


class BudgetResponse(TypedDict):
    budgeted_amount: str
    currency_code: str


class Field(TypedDict):
    name: str
    value: list[str]


class Links7(TypedDict):
    campaign: str
    self: str


class CampaignBriefTemplateValue(TypedDict):
    id: str
    name: str


class Links8(TypedDict):
    campaign: str
    comment_by: str


class CampaignCommentResponse(TypedDict):
    attachments: list[AttachmentResponse]
    comment_by: str
    created_at: str
    id: str
    is_resolved: bool
    links: Links8
    modified_at: str
    parent_comment_id: str | None
    value: str


class CampaignCreateRequest(TypedDict):
    color: NotRequired[
        Literal[
            "#333",
            "#ec2e3b",
            "#fc594b",
            "#e2575b",
            "#f45097",
            "#de55a9",
            "#bd417f",
            "#a959cc",
            "#6456b7",
            "#4db2fc",
            "#3a97be",
            "#36c5a3",
            "#9bc94e",
            "#fdad3c",
            "#ef803c",
            "#fd8876",
            "#ea868a",
            "#f781b5",
            "#e785c1",
            "#cf69a3",
            "#c187db",
            "#9086cc",
            "#79c8fd",
            "#5ab5d0",
            "#4fd5bd",
            "#b8d877",
            "#fec454",
            "#f3a35a",
            "#d3998f",
            "#c79697",
            "#d096af",
            "#c897b4",
            "#ae7c98",
            "#b094be",
            "#908bae",
            "#97bed8",
            "#7aa8b6",
            "#7abeb2",
            "#bece9d",
            "#e3c68d",
            "#d3ac85",
            "#b9a29e",
            "#b29f9f",
            "#b9a1ac",
            "#b5a1ae",
            "#9a8692",
            "#a89bac",
            "#908e9b",
            "#a8b9c3",
            "#8ea1a7",
            "#96b1ac",
            "#c1c8b5",
            "#d4c8b0",
            "#c0b0a1",
            "#212121",
            "#CE515B",
            "#F16281",
            "#EB7777",
            "#A25555",
            "#B05F8C",
            "#AF8EC3",
            "#21B7EC",
            "#3AB0C9",
            "#669BA8",
            "#7ABEB2",
            "#5F9DCE",
            "#717CB9",
            "#4C557E",
            "#449C6C",
            "#63B05F",
            "#4D9B93",
            "#ACC050",
            "#A29F55",
            "#8AA872",
            "#E4844C",
            "#EE9808",
            "#DE7009",
            "#FCD404",
            "#CBB039",
            "#99896A",
            "#2e2a26",
            "#ccccdc",
        ]
    ]
    description: NotRequired[str | None]
    end_date: NotRequired[str]
    owner_id: NotRequired[str]
    parent_campaign: NotRequired[str | None]
    start_date: NotRequired[str]
    title: str


CampaignFieldTypes: TypeAlias = Literal[
    "checkbox",
    "currency_number",
    "date",
    "dropdown",
    "label",
    "radio_button",
    "text_area",
    "percentage_number",
    "rich_text",
    "simple_number",
    "text",
    "image",
    "video",
]


class Links9(TypedDict):
    campaign: str
    campaign_fields: str


class CampaignFieldUpdateResponse(TypedDict):
    id: str
    links: Links9
    name: str
    type: CampaignFieldTypes
    values: list[str]


class Links10(TypedDict):
    self: str


class Owner(TypedDict):
    id: NotRequired[str]


class CampaignListResponseItem(TypedDict):
    description: str | None
    end_date: str | None
    id: str
    is_hidden: bool
    links: Links10
    owner: Owner
    reference_id: str
    start_date: str | None
    title: str


class Links11(TypedDict):
    brief: str | None
    child_campaigns: list[str]
    owner: str | None
    parent_campaign: str | None
    self: str


class CampaignUpdateRequest(TypedDict):
    end_date: NotRequired[str | None]
    owner_id: NotRequired[str]
    start_date: NotRequired[str | None]
    title: NotRequired[str]


class Choice4(TypedDict):
    name: str


class CheckboxAndRadioTypeSettingsFieldCreatePayload(BaseSettingsFieldCreatePayload):
    choices: list[Choice4]


class Choice5(TypedDict):
    id: str
    name: str


class CheckboxAndRadioTypeSettingsFieldResponse(BaseSettingsFieldsResponse):
    choices: list[Choice5]


ChoiceDisplayOption: TypeAlias = Literal["radio", "dropdown", "tag", "checkbox"]


class ChoiceFieldValueModel(TypedDict):
    choice_key: str
    order_index: NotRequired[int]


class CommentCreateRequest(TypedDict):
    attachments: NotRequired[list[AttachmentRequest]]
    value: str


class CommentWithReplyCreateRequest(TypedDict):
    attachments: NotRequired[list[AttachmentRequest]]
    parent_comment_id: NotRequired[str]
    value: str


class Links12(TypedDict):
    definition: NotRequired[str]
    self: NotRequired[str]


class ContentFieldValueModel(TypedDict):
    content_guid: str
    content_url: NotRequired[str]
    embedded: bool
    order_index: NotRequired[int]


class ContentMigrationSummary(TypedDict):
    errored: NotRequired[int]
    not_started: NotRequired[int]
    skipped: NotRequired[int]
    succeeded: NotRequired[int]
    total: NotRequired[int]


ContentTypeFieldEmbedMixConfig: TypeAlias = Literal[1, 2, 3]


ContentTypeListingOption: TypeAlias = Literal["1", "2", "3"]


class CoreContentType(TypedDict):
    component: bool
    description: NotRequired[str]
    disabled: NotRequired[bool]
    name: str
    thumbnail_guid: NotRequired[str]


class CreativeAssetRequest(TypedDict):
    key: str
    name: str


class CreativeAssetResponse(TypedDict):
    id: str
    name: str
    url: str


class CurrencyCustomField(TypedDict):
    currency_code: str
    decimal_places: int | None
    has_thousand_separator: bool
    label: str


class DateTypeFormFieldRequest(BaseFormFieldRequest):
    values: NotRequired[list[str]]


class DateTypeFormFieldResponse(BaseFormFieldResponse):
    values: NotRequired[list[str]]


class DateTypeObjectFieldUpdatePayload(BaseObjectFieldUpdatePayload):
    values: NotRequired[list[str]]


class DatetimeFieldValueModel(TypedDict):
    datetime_value: str
    order_index: NotRequired[int]


class DeleteFieldValueModel(TypedDict):
    delete: bool
    order_index: NotRequired[int]


class DeleteLocaleFieldValueModel(TypedDict):
    delete: bool
    locale: str


class DetailedAssetRenditionResponse(BaseAssetRenditionResponse):
    alt_text: str | None
    asset_type: str
    height: int | None
    modified_at: str
    original_asset_id: str
    rendition_config_id: NotRequired[str]
    status: Literal["Done", "InProgress", "Error"]
    width: int | None


class DropdownTypeObjectFieldUpdatePayload(BaseObjectFieldUpdatePayload):
    values: NotRequired[list[str]]


class Choice6(TypedDict):
    name: str


class DropdownTypeSettingsFieldCreatePayload(BaseSettingsFieldCreatePayload):
    choices: list[Choice6]
    is_multi_select: bool


class Choice7(TypedDict):
    id: str
    name: str


class DropdownTypeSettingsFieldResponse(BaseSettingsFieldsResponse):
    choices: list[Choice7]
    is_multi_select: bool


class Error(TypedDict):
    errors: NotRequired[dict[str, Any]]
    message: str


class Links13(TypedDict):
    campaign: str | None
    self: str


class EventResponse(TypedDict):
    campaign_id: str | None
    created_by: str
    description: str | None
    end_date: str
    id: str
    is_all_day: bool
    is_archived: bool
    links: Links13
    reference_id: str
    start_date: str
    title: str


class EventUpdateRequest(TypedDict):
    description: NotRequired[str]
    end_date: NotRequired[str]
    is_all_day: NotRequired[bool]
    start_date: NotRequired[str]
    title: NotRequired[str]


class Source(TypedDict):
    name: str | None


class FeaturedImageResponse(TypedDict):
    attribution_text: str | None
    caption: str
    description: str | None
    height: int
    mime_type: str
    source: Source
    thumbnail: str | None
    url: str
    width: int


class FieldBaseType(TypedDict):
    id: str
    name: str
    type: str
    values: list[str]


FieldType: TypeAlias = Literal[
    "boolean",
    "number",
    "text-field",
    "rich-text",
    "datetime",
    "library-asset",
    "content-type",
    "json",
    "url",
    "choice",
    "location",
]


class FieldTypeCheckbox(FieldBaseType):
    choices: list[Choice7]


class FieldTypeCommon(FieldBaseType):
    pass


class FieldTypeCurrencyNumber(FieldBaseType):
    currency_code: str
    decimal_places: int | None
    has_thousand_separator: bool


class FieldTypeDropdown(FieldBaseType):
    choices: list[Choice7]
    is_multi_select: bool


class FieldTypeLabel(FieldBaseType):
    choices: list[Choice7]
    is_multi_select: bool


class FieldTypePercentageNumber(FieldBaseType):
    decimal_places: int | None


class FieldTypeRadio(FieldBaseType):
    choices: list[Choice7]


class FieldTypeSimpleNumber(FieldBaseType):
    decimal_places: int | None
    has_thousand_separator: bool


class FileTypeFormFieldValueRequest(TypedDict):
    key: str
    name: str


class FileTypeFormFieldValueResponse(TypedDict):
    id: str
    name: str
    url: str


class FileUrlBulkCreateRequest(TypedDict):
    guids: list[str]


class FolderCreateRequest(TypedDict):
    name: str
    parent_folder_id: NotRequired[str | None]


class FolderPermissionBulkCreateRequest(TypedDict):
    permissions: list[Permission]
    type: Literal["user", "team"]


class FolderPermissionUpdateRequest(TypedDict):
    access_type: NotRequired[Literal["view", "edit"]]
    is_owner: NotRequired[bool]


class Links14(TypedDict):
    assets: str
    child_folders: str
    parent_folder: str | None
    self: str


class FolderResponse(TypedDict):
    created_at: str
    id: str
    links: Links14
    modified_at: str
    name: str
    parent_folder_id: str | None
    path: str


class FolderUpdateRequest1(TypedDict):
    name: str
    parent_folder_id: NotRequired[str | None]


class FolderUpdateRequest2(TypedDict):
    name: NotRequired[str]
    parent_folder_id: str | None


FolderUpdateRequest: TypeAlias = FolderUpdateRequest1 | FolderUpdateRequest2


class GenericNumberTypeSettingsFieldCreatePayload(BaseSettingsFieldCreatePayload):
    decimal_places: NotRequired[int]
    has_thousand_separator: NotRequired[bool]


class GenericNumberTypeSettingsFieldResponse(BaseSettingsFieldsResponse):
    decimal_places: int
    has_thousand_separator: bool


class GenericNumberTypeSettingsFieldUpdatePayload(BaseSettingsFieldUpdatePayload):
    decimal_places: NotRequired[int]
    has_thousand_separator: NotRequired[bool]


class GenericSettingsFieldChoiceCreatePayload(TypedDict):
    name: str


class GenericSettingsFieldChoiceUpdatePayload(TypedDict):
    name: str


class HTTPException(TypedDict):
    detail: NotRequired[str]


class Instruction(TypedDict):
    description: str
    id: str


class JSONFieldValueModel(TypedDict):
    json_value: dict[str, Any] | list[Any]
    order_index: NotRequired[int]


class KeyedPreviewCompletedModel(TypedDict):
    completed: str
    locale: NotRequired[str]
    mimeType: NotRequired[str]
    name: NotRequired[str]
    orderIndex: NotRequired[float]


class KeyedPreviewErrorModel(TypedDict):
    error: str
    locale: NotRequired[str]
    mimeType: NotRequired[str]
    name: NotRequired[str]
    orderIndex: NotRequired[float]


class LabelAndDropdownTypeSettingsFieldUpdatePayload(BaseSettingsFieldUpdatePayload):
    is_multi_select: NotRequired[bool]


class LabelGroupValue(TypedDict):
    id: str
    name: str


class LabelOnlyCustomField(TypedDict):
    label: str


class LabelTypeSettingsFieldChoiceCreatePayload(
    GenericSettingsFieldChoiceCreatePayload
):
    color: str


class LabelTypeSettingsFieldChoiceUpdatePayload(TypedDict):
    color: NotRequired[str]
    name: NotRequired[str]


class Choice12(TypedDict):
    color: str
    name: str


class LabelTypeSettingsFieldCreatePayload(BaseSettingsFieldCreatePayload):
    choices: list[Choice12]
    is_multi_select: bool


class Choice13(TypedDict):
    color: str | None
    id: str
    name: str


class LabelTypeSettingsFieldResponse(BaseSettingsFieldsResponse):
    choices: list[Choice13]
    is_multi_select: bool


class LibraryAssetCreateRequest(TypedDict):
    folder_id: NotRequired[str | None]
    key: str
    title: str


LibraryAssetType: TypeAlias = Literal[
    "article", "image", "video", "raw_file", "structured_content"
]


class Content(TypedDict):
    type: Literal["url"]
    value: str


class Links15(TypedDict):
    asset: str


class LibraryAssetVersionResponse(TypedDict):
    asset_id: str
    content: Content
    created_at: str
    links: Links15
    mime_type: str
    title: str
    type: Literal["image", "video", "raw_file"]
    version_number: int


class FocalPoint(TypedDict):
    x: int
    y: int


class ImageResolution(TypedDict):
    height: int
    width: int


Tag1: TypeAlias = str


class Links16(TypedDict):
    self: str


class Fields1(TypedDict):
    has_embedded: NotRequired[bool | None]


class ContentBody(TypedDict):
    content_type_guid: str
    expired: NotRequired[bool]
    expiry_datetime: NotRequired[str | None]
    fields: NotRequired[Fields1 | None]
    root_content: bool
    source: NotRequired[str | None]
    source_id: NotRequired[str | None]
    source_metadata: NotRequired[str | None]
    title: NotRequired[str]


class LibraryStructuredContentCreateRequest(TypedDict):
    content_body: ContentBody
    folder_id: NotRequired[str | None]
    title: NotRequired[str]


class LocationDefaultValue(TypedDict):
    latitude: float
    longitude: float


class LocationFieldValueModel(TypedDict):
    latitude: float
    longitude: float
    order_index: NotRequired[int]


class TargetField(TypedDict):
    custom_field_type: str | None
    identifier: str
    type: str


class Action(TypedDict):
    target_field: TargetField
    type: str
    values: list[str]


class Condition(TypedDict):
    operator: str
    values: list[str]


class LogicRule(TypedDict):
    action: Action
    condition: Condition


class LogicRuleAction(TypedDict):
    target_field: TargetField
    type: str
    values: list[str]


class LogicRuleCondition(TypedDict):
    operator: str
    values: list[str]


class LogicRuleTargetField(TypedDict):
    custom_field_type: str | None
    identifier: str
    type: str


class Task(TypedDict):
    id: str


class MilestoneCreateRequest(TypedDict):
    campaign_id: NotRequired[str]
    description: NotRequired[str | None]
    due_date: str
    hex_color: str
    tasks: NotRequired[list[Task]]
    title: str


class Campaign(TypedDict):
    id: str


class MilestoneResponse(TypedDict):
    campaign: Campaign | None
    color: str
    description: str | None
    due_date: str
    id: str
    links: Links16
    title: str


class MilestoneUpdateRequest(TypedDict):
    campaign_id: NotRequired[str]
    description: NotRequired[str | None]
    due_date: NotRequired[str]
    hex_color: NotRequired[str]
    tasks: NotRequired[list[Task]]
    title: NotRequired[str]


class MultiChoiceTypeFormFieldRequest(BaseFormFieldRequest):
    values: NotRequired[list[str]]


class Value1(TypedDict):
    id: str
    name: str


class MultiChoiceTypeFormFieldResponse(BaseFormFieldResponse):
    values: NotRequired[list[Value1]]


class MultiChoiceTypeObjectFieldUpdatePayload(BaseObjectFieldUpdatePayload):
    values: NotRequired[list[str]]


class MultipleOptionCustomField(TypedDict):
    choices: list[str]
    label: str


class NumberCustomField(TypedDict):
    decimal_places: int | None
    has_thousand_separator: bool
    label: str


class NumberFieldValueModel(TypedDict):
    num_value: float
    order_index: NotRequired[int]


Value2: TypeAlias = float


class NumberTypeFormFieldRequest(BaseFormFieldRequest):
    values: NotRequired[list[Value2]]


class NumberTypeFormFieldResponse(BaseFormFieldResponse):
    values: NotRequired[list[str]]


class NumberTypeObjectFieldUpdatePayload(BaseObjectFieldUpdatePayload):
    values: NotRequired[list[float]]


ObjectFieldCreateResponse: TypeAlias = (
    FieldTypeCommon
    | FieldTypeLabel
    | FieldTypeDropdown
    | FieldTypeRadio
    | FieldTypeCheckbox
    | FieldTypeSimpleNumber
    | FieldTypePercentageNumber
    | FieldTypeCurrencyNumber
)


class Pagination(TypedDict):
    next: str | None
    previous: str | None


class PercentageCustomField(TypedDict):
    decimal_places: int | None
    label: str


class Pagination2(Pagination):
    next: NotRequired[str | None]


class PublishingChannelResponse(TypedDict):
    disabled: bool | None
    id: str
    name: str | None


class PublishingMetadatum(TypedDict):
    id: str
    links: Links16


class PublishingEventAssets(TypedDict):
    id: str
    links: Links16
    publishing_metadata: list[PublishingMetadatum]
    type: str


class Error1(TypedDict):
    asset_id: str
    error_code: Literal[
        "canonical-link-error",
        "unknown-asset",
        "metadata-exists",
        "duplicate-metadata",
        "invalid-status",
        "missing-public-url",
        "public-url-not-allowed",
        "domain-not-whitelisted",
        "missing-publishing-destination-updated-at",
        "publishing-destination-updated-at-not-allowed",
        "missing-locale",
        "locale-not-allowed",
    ]
    locale: str | None
    message: str


class PublishingEventMetadataCreateRequest(TypedDict):
    asset_id: str
    locale: NotRequired[str]
    public_url: NotRequired[str]
    publishing_destination_updated_at: NotRequired[str]
    status: Literal["published", "unpublished", "synced", "failed"]
    status_message: NotRequired[str]


class Links20(TypedDict):
    asset: str
    publishing_event: str
    self: str


class PublishingEventMetadataResponse(TypedDict):
    asset_id: str
    asset_type: Literal["article", "image", "video", "raw_file", "structured_content"]
    id: str
    links: Links20
    locale: str | None
    public_url: str | None
    publishing_destination_updated_at: str | None
    status: Literal["published", "unpublished", "synced", "failed"] | None
    status_message: str | None


class Links21(TypedDict):
    publishing_metadata: str
    self: str


class PublishingEventResponse(TypedDict):
    assets: list[PublishingEventAssets]
    id: str
    links: Links21


class RadioButtonTypeFormFieldRequest(BaseFormFieldRequest):
    values: NotRequired[list[str]]


class Value3(TypedDict):
    id: str
    name: str


class RadioButtonTypeFormFieldResponse(MultiChoiceTypeFormFieldResponse):
    values: NotRequired[list[Value3]]


class RadioButtonTypeObjectFieldUpdatePayload(BaseObjectFieldUpdatePayload):
    values: NotRequired[list[str]]


class RecursiveStructuredContent(TypedDict):
    content_type_guid: str
    expired: NotRequired[bool]
    expiry_datetime: NotRequired[str | None]
    root_content: bool
    source: NotRequired[str | None]
    source_id: NotRequired[str | None]
    source_metadata: NotRequired[str | None]
    title: NotRequired[str]


class Content1(TypedDict):
    type: Literal["url", "api_url", "html_body"]
    value: str


class Links22(TypedDict):
    self: str


class RelatedAssetItem(TypedDict):
    content: Content1
    file_extension: str | None
    id: str
    links: Links22
    mime_type: str | None
    title: str
    type: Literal["article", "image", "video", "raw_file", "structured_content"]


class RelatedAssetsListResponse(TypedDict):
    data: list[RelatedAssetItem]
    pagination: Pagination2


class RenditionConfigResponse(TypedDict):
    asset_type: str
    height: int | None
    id: str
    input_format: str | None
    name: str
    output_format: str | None
    quality: float | None
    width: int | None


class RelatedAsset(TypedDict):
    id: str


class ReplaceRelatedAssetsRequest(TypedDict):
    related_assets: list[RelatedAsset]


class ReplaceRelatedAssetsResponse(TypedDict):
    id: str
    related_assets: list[RelatedAsset]


class ResourceChoiceResponse(TypedDict):
    id: str
    name: str


class ResourceLabelRequest(TypedDict):
    group: str
    values: list[str]


class Group(TypedDict):
    id: str
    name: str


class ResourceLabelResponse(TypedDict):
    group: Group
    values: list[Value3]


class RichTextFieldValueModel(TypedDict):
    order_index: NotRequired[int]
    rich_text_value: str


class SCContentPreviewAcknowledgeRequest(TypedDict):
    acknowledged_by: str
    content_hash: str


class SCContentPreviewCompleteRequest(TypedDict):
    keyed_previews: dict[str, str | KeyedPreviewCompletedModel | KeyedPreviewErrorModel]


class SCContentTypeCreateResponse(TypedDict):
    content_type_guid: NotRequired[str]
    content_type_version_guid: NotRequired[str]
    created: bool


class SCContentTypeManagedMigrationResponse(TypedDict):
    content_migration_summary: NotRequired[ContentMigrationSummary]
    content_type_id: NotRequired[str]
    created_at: NotRequired[str]
    default_values: NotRequired[dict[str, Any]]
    id: NotRequired[str]
    instance_id: NotRequired[str]
    source_content_type_version_id: NotRequired[str]
    status: NotRequired[Literal["not_started", "in_progress", "success", "error"]]
    target_content_type_version_id: NotRequired[str]
    updated_at: NotRequired[str]


class SCContentTypeManagedMigrationStartResponse(TypedDict):
    job_id: NotRequired[str]
    started: NotRequired[bool]


class SCContentTypeUpdateRequest(TypedDict):
    details: CoreContentType
    source_metadata: NotRequired[str]
    updated_by: str


class SCContentTypeUpdateResponse(TypedDict):
    updated: bool


class Section(TypedDict):
    id: str
    label: str


class CustomFields(TypedDict):
    checkbox: list[MultipleOptionCustomField]
    currency: list[CurrencyCustomField]
    date: list[LabelOnlyCustomField]
    dropdown: list[MultipleOptionCustomField]
    image: list[LabelOnlyCustomField]
    multi_select_dropdown: list[MultipleOptionCustomField]
    multichoice: list[MultipleOptionCustomField]
    number: list[NumberCustomField]
    percentage: list[PercentageCustomField]
    richtext: list[LabelOnlyCustomField]
    string: list[LabelOnlyCustomField]
    textarea: list[LabelOnlyCustomField]
    video: list[LabelOnlyCustomField]


class SettingsApp(TypedDict):
    authorization_callback_urls: list[str]
    description: str
    env: str
    expose_email: bool
    homepage_url: str
    name: str


class Create(TypedDict):
    apps: list[str]
    custom_fields: list[str]
    labels: list[str]
    routing_rules: list[str]
    templates: list[str]
    webhooks: list[str]
    workflows: list[str]


class Update(TypedDict):
    apps: list[str]
    custom_fields: list[str]
    labels: list[str]
    routing_rules: list[str]
    templates: list[str]
    webhooks: list[str]
    workflows: list[str]


class SettingsChangeset(TypedDict):
    create: Create
    update: Update


class SettingsChangesetBase(TypedDict):
    apps: list[str]
    custom_fields: list[str]
    labels: list[str]
    routing_rules: list[str]
    templates: list[str]
    webhooks: list[str]
    workflows: list[str]


class SettingsCustomField(TypedDict):
    checkbox: list[MultipleOptionCustomField]
    currency: list[CurrencyCustomField]
    date: list[LabelOnlyCustomField]
    dropdown: list[MultipleOptionCustomField]
    image: list[LabelOnlyCustomField]
    multi_select_dropdown: list[MultipleOptionCustomField]
    multichoice: list[MultipleOptionCustomField]
    number: list[NumberCustomField]
    percentage: list[PercentageCustomField]
    richtext: list[LabelOnlyCustomField]
    string: list[LabelOnlyCustomField]
    textarea: list[LabelOnlyCustomField]
    video: list[LabelOnlyCustomField]


SettingsFieldChoiceCreateRequest: TypeAlias = list[
    GenericSettingsFieldChoiceCreatePayload | LabelTypeSettingsFieldChoiceCreatePayload
]


class SettingsFieldChoiceCreateResponseItem(TypedDict):
    id: str
    name: str


SettingsFieldChoiceCreateResponse: TypeAlias = list[
    SettingsFieldChoiceCreateResponseItem
]


SettingsFieldChoiceUpdateRequest: TypeAlias = (
    GenericSettingsFieldChoiceUpdatePayload | LabelTypeSettingsFieldChoiceUpdatePayload
)


class SettingsLabelGroupLabel(TypedDict):
    color: str | None
    name: str


class Rule(TypedDict):
    custom_field_type: str | None
    field_type: str
    identifier: str | None
    operator: str
    unit: Literal["days", "weeks", "months", "years"] | None
    value: list[str]


class SettingsRoutingRule(TypedDict):
    description: str
    name: str
    rules: list[Rule]
    template_name: str | None
    watchers: list[str]


class Changeset(TypedDict):
    create: Create
    update: Update


class SettingsWebhook(TypedDict):
    callback_url: str
    description: str
    event_names: list[str]
    name: str
    secret: str


class StringTypeObjectFieldUpdatePayload(BaseObjectFieldUpdatePayload):
    values: NotRequired[list[str]]


class StructuredContentBody(TypedDict):
    has_embedded: NotRequired[bool | None]


class Tag(TypedDict):
    guid: str
    name: str


class WebUrls(TypedDict):
    drafts: str | None
    self: str
    task: str


class Links23(TypedDict):
    drafts: str | None
    self: str
    task: str
    web_urls: WebUrls


class TaskArticle(TypedDict):
    created_at: str
    html_body: str
    id: str
    labels: list[ResourceLabelResponse]
    library_asset_id: NotRequired[str | None]
    links: Links23
    modified_at: str
    title: str
    url: str | None


class Links24(TypedDict):
    asset: str
    task: str


class TaskAssetCommentResponse(TypedDict):
    attachments: list[AttachmentResponse]
    created_at: str
    id: str
    is_resolved: bool
    links: Links24
    modified_at: str
    value: str


class Criterion1(TypedDict):
    description: str | None
    id: str
    selected: bool | None


class Category(TypedDict):
    criteria: list[Criterion1]
    id: str
    notes: str | None
    status: Literal["compliant", "not compliant", "not applicable"] | None


class TaskAssetDraftBrandComplianceRequest(TypedDict):
    categories: list[Category]
    status: Literal["approved", "declined", "not_reviewed"]


class Criterion2(TypedDict):
    description: str | None
    id: str
    name: str
    selected: bool | None


class Category1(TypedDict):
    criteria: list[Criterion2]
    id: str
    name: str
    notes: str | None
    status: Literal["compliant", "not compliant", "not applicable"] | None


class TaskAssetDraftBrandComplianceResponse(TypedDict):
    categories: list[Category1]
    reviewed_at: str | None
    reviewed_by: str | None
    status: Literal["approved", "declined", "not_reviewed"]


class Content2(TypedDict):
    type: Literal["url"]
    value: str


class TaskAssetDraftListResponseItem(TypedDict):
    content: Content2
    created_at: str
    draft_number: int
    id: str
    links: Links24
    mime_type: str
    title: str
    type: Literal["image", "video", "raw_file"]


class TaskAssetDraftResponse(TypedDict):
    asset_id: str
    content: Content2
    created_at: str
    draft_number: int
    links: Links24
    mime_type: str
    title: str
    type: Literal["image", "video", "raw_file"]


class TaskAssetRequestForDirectUpload(TypedDict):
    key: str
    title: str
    type: NotRequired[str]


class TaskAssetRequestForLibrary(TypedDict):
    content_id: str
    content_type: Literal["article", "image", "raw_file", "structured_content", "video"]
    type: str


class Links27(TypedDict):
    drafts: str | None
    self: str
    task: str
    web_urls: WebUrls


class TaskAssetResponse(TypedDict):
    content: AssetContent
    created_at: str
    id: str
    labels: list[ResourceLabelResponse]
    links: Links27
    mime_type: str
    modified_at: str
    title: str
    type: Literal["article", "image", "video", "raw_file", "structured_content"]


class Field1(TypedDict):
    name: str
    settings_field_id: NotRequired[str | None]
    value: list[str]


class Links28(TypedDict):
    self: str
    task: str


class TaskBriefTemplateValue(TypedDict):
    id: str
    name: str


class Links29(TypedDict):
    comment_by: str
    task: str


class TaskCommentResponse(TypedDict):
    attachments: list[AttachmentResponse]
    comment_by: str
    created_at: str
    id: str
    is_resolved: bool
    links: Links29
    modified_at: str
    parent_comment_id: str | None
    value: str


class TaskCreateRequest(TypedDict):
    campaign_id: NotRequired[str]
    due_at: NotRequired[str]
    owner_id: NotRequired[str]
    start_at: NotRequired[str]
    title: str
    workflow_id: NotRequired[str]


class Links30(TypedDict):
    choices: str | None
    self: str


class Value5(TypedDict):
    id: str | None
    name: str


class TaskCustomField(TypedDict):
    id: str
    links: Links30
    name: str
    type: Literal[
        "text_field",
        "multi_line_text_field",
        "checkboxes",
        "dropdown",
        "multi_select_dropdown",
        "multiple_choice",
        "date_field",
        "image",
        "video",
        "rich_text_field",
    ]
    values: list[Value5]


class TaskCustomFieldChoiceListResponseItem(TypedDict):
    id: str
    name: str


class TaskCustomFieldUpdateRequest(TypedDict):
    values: list[str]


class TaskExternalWorkRequest(TypedDict):
    identifier: NotRequired[str | None]
    status: NotRequired[str | None]
    title: NotRequired[str | None]
    url: NotRequired[str | None]


class Links31(TypedDict):
    self: str


class TaskExternalWorkResponse(TypedDict):
    external_system: str
    identifier: str | None
    links: Links31
    status: str | None
    title: str | None
    url: str | None


class WebUrls2(TypedDict):
    drafts: str
    self: str
    task: str


class Links32(TypedDict):
    drafts: str
    self: str
    task: str
    web_urls: WebUrls2


class TaskImage(TypedDict):
    created_at: str
    file_size: int
    id: str
    image_resolution: ImageResolution
    labels: list[ResourceLabelResponse]
    library_asset_id: NotRequired[str | None]
    links: Links32
    mime_type: str
    modified_at: str
    title: str
    url: str


class WebUrls3(TypedDict):
    self: str


class Links33(TypedDict):
    campaign: str | None
    milestone: str | None
    self: str
    web_urls: WebUrls3
    workflow: str | None


class TaskListResponseItem(TypedDict):
    campaign_id: str | None
    due_at: str | None
    id: str
    is_archived: bool
    is_completed: bool
    links: Links33
    milestone_id: str | None
    modified_at: str | None
    reference_id: str
    start_at: str | None
    status: Literal[
        "Archived", "Completed", "Overdue", "Not Started", "In Progress", "On Hold"
    ]
    title: str
    workflow_id: str | None


class TaskPublishingIntentCreateRequest(TypedDict):
    channel_id: str


class TaskPublishingIntentResponse(TypedDict):
    id: str


class WebUrls4(TypedDict):
    drafts: str
    self: str
    task: str


class Links34(TypedDict):
    drafts: str
    self: str
    task: str
    web_urls: WebUrls4


class TaskRawFile(TypedDict):
    created_at: str
    file_size: int
    id: str
    labels: list[ResourceLabelResponse]
    library_asset_id: NotRequired[str | None]
    links: Links34
    mime_type: str
    modified_at: str
    title: str
    url: str


class WebUrls5(TypedDict):
    brief: str
    self: str


class Links35(TypedDict):
    assets: str
    attachments: str
    brief: str | None
    campaign: str
    custom_fields: str | None
    milestone: str | None
    self: str
    web_urls: WebUrls5


class TaskStepRequest(TypedDict):
    due_at: NotRequired[str]


class TaskStructuredContentCreateRequest(TypedDict):
    content_type_guid: str
    expired: NotRequired[bool]
    expiry_datetime: NotRequired[str | None]
    fields: NotRequired[Fields1 | None]
    primary_locale: NotRequired[str]
    root_content: NotRequired[bool]
    source: NotRequired[str | None]
    source_id: NotRequired[str | None]
    source_metadata: NotRequired[str | None]
    template_guid: NotRequired[str]
    title: NotRequired[str]


class Links36(TypedDict):
    assignee: NotRequired[str | None]
    external_work: str | None
    self: str
    task: str


class TaskSubStep(TypedDict):
    assignee_id: str | None
    assignee_type: Literal["user", "team"]
    id: str
    is_completed: bool
    is_external: bool
    is_in_progress: bool
    is_skipped: bool
    links: Links36
    title: str


class Links37(TypedDict):
    comment_by: str
    self: str
    sub_step: str
    task: str


class TaskSubStepCommentResponse(TypedDict):
    attachments: list[AttachmentResponse]
    created_at: str
    id: str
    is_resolved: bool
    links: NotRequired[Links37]
    modified_at: str
    value: str


class TaskSubStepCommentUpdateRequest(TypedDict):
    value: str


class TaskSubStepRequest(TypedDict):
    assignee_id: NotRequired[str | None]
    assignee_type: NotRequired[Literal["user", "team"]]
    is_completed: NotRequired[Literal[True]]
    is_in_progress: NotRequired[Literal[True]]
    is_skipped: NotRequired[Literal[True]]


class TaskUpdateRequest(TypedDict):
    campaign_id: NotRequired[str]
    due_at: NotRequired[str]
    labels: NotRequired[list[ResourceLabelRequest]]
    owner_id: NotRequired[str]
    start_at: NotRequired[str]
    title: NotRequired[str]
    workflow_id: NotRequired[str]


class TaskUrlResponse(TypedDict):
    created_at: str
    id: str


class WebUrls6(TypedDict):
    drafts: str
    self: str
    task: str


class Links38(TypedDict):
    drafts: str
    self: str
    task: str
    web_urls: WebUrls6


class TaskVideo(TypedDict):
    created_at: str
    file_size: int
    id: str
    labels: list[ResourceLabelResponse]
    library_asset_id: NotRequired[str | None]
    links: Links38
    mime_type: str
    modified_at: str
    title: str
    url: str


class Links39(TypedDict):
    self: str


class Team(TypedDict):
    id: str
    links: Links39
    name: str


class User(TypedDict):
    email: str
    id: str
    name: str


class TeamWithUsers(TypedDict):
    id: str
    links: Links39
    name: str
    users: list[User]


class TypeSpecificMeta(TypedDict):
    choices: list[ResourceChoiceResponse]
    is_multi_select: bool


class TypeSpecificMeta1(TypedDict):
    currency_code: str
    decimal_places: int | None
    has_thousand_separator: bool


class TypeSpecificMeta2(TypedDict):
    description: str


class Datum(BaseTemplateResponse):
    links: Links39


class TemplateListResponse(TypedDict):
    data: list[Datum]
    pagination: Pagination2


class TargetField2(TypedDict):
    identifier: str


class TemplateLogicRuleAction(TypedDict):
    target_field: TargetField2
    type: Literal["jump_to", "show_values"]
    values: list[str]


class TemplateLogicRuleCondition(TypedDict):
    operator: Literal["any_of", "equal", "not_equal"]
    values: list[str]


class TypeSpecificMeta3(TypedDict):
    decimal_places: int | None


class TypeSpecificMeta4(TypedDict):
    decimal_places: int | None
    has_thousand_separator: bool


class TextFieldValueModel(TypedDict):
    order_index: NotRequired[int]
    text_value: str


class TextTypeFormFieldRequest(BaseFormFieldRequest):
    values: NotRequired[list[str]]


class TextTypeFormFieldResponse(BaseFormFieldResponse):
    values: NotRequired[list[str]]


class URLFieldValueModel(TypedDict):
    order_index: NotRequired[int]
    url: str


class Role(TypedDict):
    name: str


class UserListResponseItem(TypedDict):
    first_name: str
    full_name: str
    id: str
    image_url: str | None
    last_name: str
    links: Links39
    roles: list[Role]


class Links45(TypedDict):
    self: NotRequired[str]


class UserResponse(TypedDict):
    email: str | None
    first_name: str
    full_name: str
    id: str
    image_url: str | None
    last_name: str
    links: NotRequired[Links45]


class ValidationError(TypedDict):
    loc: list[str]
    msg: str
    type: str


class Links46(TypedDict):
    self: NotRequired[str]
    versions: NotRequired[str]


class ContentType(TypedDict):
    type: Literal["html_body", "url"]
    value: str


class WorkRequestApprovedAssetResponse(TypedDict):
    content_type: ContentType
    id: str
    mime_type: str
    title: str
    type: Literal["article", "image", "video", "raw_file"]


class Value6(TypedDict):
    key: str
    name: str


class WorkRequestAttachmentBriefRequest(TypedDict):
    type: Literal["attachment_brief"]
    value: Value6


class Value7(TypedDict):
    id: str
    name: str
    url: str


class WorkRequestAttachmentBriefResponse(TypedDict):
    type: Literal["attachment_brief"]
    value: Value7


class WorkRequestCampaignRequest(TypedDict):
    description: NotRequired[str | None]
    end_date: NotRequired[str | None]
    owner_id: NotRequired[str]
    parent_campaign_id: NotRequired[str]
    start_date: NotRequired[str | None]
    title: str


class Links47(TypedDict):
    brief: str | None
    parent_campaign: str | None
    self: str


class WorkRequestCampaignResponse(TypedDict):
    description: str | None
    end_date: str | None
    id: str
    links: Links47
    owner_id: str
    parent_campaign_id: str
    reference_id: str
    start_date: str | None
    title: str


class Links48(TypedDict):
    comment_by: str
    work_request: str


class WorkRequestCommentResponse(TypedDict):
    attachments: list[AttachmentResponse]
    comment_by: str
    created_at: str
    id: str
    is_resolved: bool
    links: Links48
    modified_at: str
    parent_comment_id: str | None
    value: str


class Links49(TypedDict):
    self: str | None


class WorkRequestRelatedResourceResponse(TypedDict):
    created_at: str
    id: str
    links: Links49
    relation_type: Literal["started", "linked"]
    resource_type: str


class WorkRequestRequestFormFieldCheckboxTypePayload(TypedDict):
    type: Literal["checkbox"]
    values: list[str]


class Value8(TypedDict):
    id: str
    name: str


class WorkRequestRequestFormFieldCheckboxTypeResponse(TypedDict):
    type: Literal["checkbox"]
    values: list[Value8]


class WorkRequestRequestFormFieldCurrencyNumberTypePayload(TypedDict):
    type: Literal["currency_number"]
    values: list[str]


class WorkRequestRequestFormFieldDateTypePayload(TypedDict):
    type: Literal["date"]
    values: list[str]


class WorkRequestRequestFormFieldDropdownTypePayload(TypedDict):
    type: Literal["dropdown"]
    values: list[str]


class WorkRequestRequestFormFieldDropdownTypeResponse(TypedDict):
    type: Literal["dropdown"]
    values: list[Value8]


class Value10(TypedDict):
    key: str
    name: str


class WorkRequestRequestFormFieldFileTypePayload(TypedDict):
    type: Literal["file"]
    values: list[Value10]


class Value11(TypedDict):
    id: str
    name: str
    url: str


class WorkRequestRequestFormFieldFileTypeResponse(TypedDict):
    type: Literal["file"]
    values: list[Value11]


class WorkRequestRequestFormFieldLabelTypePayload(TypedDict):
    type: Literal["label"]
    values: list[str]


class Value12(TypedDict):
    id: str
    name: str


class WorkRequestRequestFormFieldLabelTypeResponse(TypedDict):
    type: Literal["label"]
    values: list[Value12]


class WorkRequestRequestFormFieldPercentageNumberTypePayload(TypedDict):
    type: Literal["percentage_number"]
    values: list[str]


class WorkRequestRequestFormFieldRadioButtonTypePayload(TypedDict):
    type: Literal["radio_button"]
    values: list[str]


class Value13(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]


class WorkRequestRequestFormFieldRadioButtonTypeResponse(TypedDict):
    type: Literal["radio_button"]
    values: list[Value13]


class WorkRequestRequestFormFieldRichtextTypePayload(TypedDict):
    type: Literal["richtext"]
    values: list[str]


class WorkRequestRequestFormFieldSimpleNumberTypePayload(TypedDict):
    type: Literal["simple_number"]
    values: list[str]


class WorkRequestRequestFormFieldTextAreaTypePayload(TypedDict):
    type: Literal["text_area"]
    values: list[str]


class WorkRequestRequestFormFieldTextTypePayload(TypedDict):
    type: Literal["text"]
    values: list[str]


class Links50(TypedDict):
    self: str


class Assignee(TypedDict):
    full_name: str
    id: str
    image_url: str | None
    links: Links50
    type: Literal["user", "team"]


class CreatedBy(TypedDict):
    id: str
    links: Links50


class Links52(TypedDict):
    attachments: str
    campaigns: str
    comments: str
    creative_assets: str
    related_resources: str
    self: str
    tasks: str


class Links53(TypedDict):
    self: str


class Template(TypedDict):
    id: str
    links: Links53
    title: str


class WorkRequestTaskRequest(TypedDict):
    asset_ids_without_field_inheritance: NotRequired[list[str]]
    campaign_id: NotRequired[str | None]
    due_at: NotRequired[str | None]
    inherit_fields_from: NotRequired[str]
    owner_id: NotRequired[str | None]
    start_at: NotRequired[str | None]
    title: NotRequired[str]
    workflow_id: NotRequired[str | None]


class Links54(TypedDict):
    owner: NotRequired[str | None]
    self: str


class WorkRequestTaskResponse(TypedDict):
    due_at: str | None
    id: str
    links: Links54
    owner_id: str
    reference_id: NotRequired[str]
    start_at: str | None
    title: str


class WorkRequestTextBriefRequest(TypedDict):
    type: Literal["text_brief"]
    value: str


class WorkRequestTextBriefResponse(TypedDict):
    type: Literal["text_brief"]
    value: str


class WorkRequestUpdateRequest(TypedDict):
    assignees: NotRequired[list[str]]
    priority: NotRequired[Literal["Low", "Medium", "High"]]
    status: NotRequired[Literal["Accepted", "Declined", "Submitted", "Completed"]]


class WorkflowChannel(TypedDict):
    display_name: str
    type: str


class WorkflowCustomfield(TypedDict):
    default_value: list[str]
    field: str
    is_required: bool
    type: str


class WorkflowLabel(TypedDict):
    default_value: list[str]
    is_required: bool
    is_required_at_task_creation: bool
    label_type: str


class WorkflowListResponseItem(TypedDict):
    description: str | None
    id: str
    is_flexible: bool
    name: str


class Action1(TypedDict):
    name: str


class Links55(TypedDict):
    self: str


class Assignee1(TypedDict):
    id: str
    links: Links55
    name: str
    type: Literal["user", "team"]


class SubStep(TypedDict):
    actions: list[Action1]
    assignees: list[Assignee1]
    id: str
    name: str
    type: Literal["default", "external"]


class Step(TypedDict):
    id: str
    name: str
    sub_steps: list[SubStep]


class WorkflowResponse(TypedDict):
    description: str | None
    fields: list[ObjectFieldCreateResponse]
    id: str
    is_active: bool
    is_asset_approval_enabled: bool
    is_flexible: bool
    is_resource_management_enabled: bool
    is_smart_duration_enabled: bool
    name: str
    steps: list[Step]


class ExternalSubStepConfig(TypedDict):
    is_user_interaction_allowed: NotRequired[bool]


class WorkflowSubStep(TypedDict):
    actions: list[str]
    description: str | None
    external_sub_step_config: NotRequired[ExternalSubStepConfig]
    external_system: str | None
    is_external: bool | None
    label: str | None


ErrorReason: TypeAlias = Literal[
    "REQUIRED_FIELD_ABSENT",
    "LIST_EMPTY",
    "INVALID_STATE",
    "INVALID_SELF_REF",
    "MIN_NOT_MET",
    "MAX_NOT_MET",
    "PATTERN_ERROR",
]


class ListAssetLineagesResponse(TypedDict):
    data: list[AssetLineageResponse]
    pagination: Pagination2


class Links56(TypedDict):
    asset_fields: str
    asset_url: str


class ListAssetRenditionsResponse(TypedDict):
    data: list[BaseAssetRenditionResponse]
    pagination: Pagination2


class ListBrandComplianceCategoriesResponse(TypedDict):
    data: list[BrandComplianceCategoriesResponse]
    pagination: Pagination2


class ListCampaignsResponse(TypedDict):
    data: list[CampaignListResponseItem]
    pagination: Pagination2


class ListEventsResponse(TypedDict):
    data: list[EventResponse]
    pagination: Pagination2


class CreateFieldResponse(TypedDict):
    id: str


class ListFoldersResponse(TypedDict):
    data: list[FolderResponse]
    pagination: Pagination2


class ListMilestonesResponse(TypedDict):
    data: list[MilestoneResponse]
    pagination: Pagination2


class Links57(TypedDict):
    complete: str
    status: str


class CreateMultipartUploadResponse(TypedDict):
    expires_at: str
    id: str
    links: Links57
    upload_part_count: int
    upload_part_urls: list[str]


class Links58(TypedDict):
    status: str


class CompleteMultipartUploadResponse(TypedDict):
    key: str
    links: Links58


class Links59(TypedDict):
    self: str


class GetMultipartUploadStatusResponse(TypedDict):
    expires_at: str
    id: str
    key: str
    links: Links59
    status: Literal[
        "UPLOAD_COMPLETION_NOT_STARTED",
        "UPLOAD_COMPLETION_IN_PROGRESS",
        "UPLOAD_COMPLETION_SUCCEEDED",
        "UPLOAD_COMPLETION_FAILED",
    ]
    status_message: str | None


ListSCContentTypesResponse: TypeAlias = list[BaseContentTypeModel]


ListSCContentTypeManagedMigrationsResponse: TypeAlias = list[
    SCContentTypeManagedMigrationResponse
]


class CreateSCContentTypeManagedMigrationResponse(TypedDict):
    created: bool


class ValidateSCContentTypeManagedMigrationResponse(TypedDict):
    is_managed_migration_possible: bool


class UpdateSCContentTypeManagedMigrationResponse(TypedDict):
    updated: NotRequired[bool]


ListSCContentTypeVersionsResponse: TypeAlias = list[BaseContentTypeVersionModel]


class MigrateSCContentResponse(TypedDict):
    content_guid: NotRequired[str]
    content_hash: NotRequired[str]
    created: NotRequired[bool]
    version_guid: NotRequired[str]


class ListTasksResponse(TypedDict):
    data: list[TaskListResponseItem]
    pagination: Pagination2


class Datum2(TaskAssetResponse):
    library_asset_id: NotRequired[str | None]


class ListTaskAssetsResponse(TypedDict):
    data: list[Datum2]
    pagination: Pagination2


class ListTaskAttachmentsResponse(TypedDict):
    data: list[AttachmentResponse]
    pagination: Pagination2


class ListTaskCustomFieldsResponse(TypedDict):
    data: list[TaskCustomField]
    pagination: Pagination2


class ListTaskAssetCommentsResponse(TypedDict):
    data: NotRequired[list[TaskAssetCommentResponse]]
    pagination: NotRequired[Pagination2]


class ListTaskAssetDraftsResponse(TypedDict):
    data: list[TaskAssetDraftListResponseItem]
    pagination: Pagination2


class ListTaskCustomFieldChoicesResponse(TypedDict):
    data: list[TaskCustomFieldChoiceListResponseItem]
    pagination: Pagination2


class ListTaskSubStepCommentsResponse(TypedDict):
    data: list[TaskSubStepCommentResponse]
    pagination: Pagination2


Data1: TypeAlias = (
    FieldTypeLabel | FieldTypeDropdown | FieldTypeRadio | FieldTypeCheckbox
)


class ListTaskSubStepFieldsResponse(TypedDict):
    data: list[Data1]
    pagination: Pagination2


class CreateTaskStructuredContentDraftResponse(TypedDict):
    pass


class ListTeamsResponse(TypedDict):
    data: list[Team]
    pagination: Pagination2


UploadMetaFields = TypedDict(
    "UploadMetaFields",
    {
        "key": str,
        "policy": str,
        "x-amz-algorithm": str,
        "x-amz-credential": str,
        "x-amz-date": str,
        "x-amz-security-token": NotRequired[str],
        "x-amz-signature": str,
    },
)


class GetUploadUrlResponse(TypedDict):
    upload_meta_fields: UploadMetaFields
    url: str


class ListWorkRequestApprovedAssetsResponse(TypedDict):
    data: list[WorkRequestApprovedAssetResponse]
    pagination: Pagination2


class ListWorkRequestCommentsResponse(TypedDict):
    data: list[WorkRequestCommentResponse]
    pagination: Pagination2


class ListWorkRequestRelatedResourcesResponse(TypedDict):
    data: list[WorkRequestRelatedResourceResponse]
    pagination: Pagination2


class ListWorkflowsResponse(TypedDict):
    data: list[WorkflowListResponseItem]
    pagination: Pagination2


class AssetFieldTypeCheckbox(BaseAssetField):
    choices: list[Choice]


class AssetFieldTypeCommon(BaseAssetField):
    pass


class AssetFieldTypeCurrencyNumber(BaseAssetField):
    currency_code: str
    decimal_places: int | None
    has_thousand_separator: bool


class AssetFieldTypeDropdown(BaseAssetField):
    choices: list[Choice]
    is_multi_select: bool


class AssetFieldTypeLabel(BaseAssetField):
    choices: list[Choice]
    is_multi_select: bool


class AssetFieldTypePercentageNumber(BaseAssetField):
    decimal_places: int | None


class AssetFieldTypeRadio(BaseAssetField):
    choices: list[Choice]


class AssetFieldTypeSimpleNumber(BaseAssetField):
    decimal_places: int | None
    has_thousand_separator: bool


class AssetPermissionListResponseItem(TypedDict):
    data: list[BasePermissionsResponseSchema]
    pagination: Pagination2


class AssetResponse(TypedDict):
    content: AssetContent
    created_at: str
    file_extension: str | None
    file_location: str
    folder_id: str | None
    id: str
    is_archived: bool
    labels: list[ResourceLabelResponse]
    links: Links2
    mime_type: str
    modified_at: str
    owner_organization_id: str
    thumbnail_url: str | None
    title: str
    type: Literal["article", "image", "video", "raw_file", "structured_content"]


class AssetTypeObjectFieldUpdatePayload(BaseObjectFieldUpdatePayload):
    values: NotRequired[list[Value]]


class BaseObjectField(BaseObjectFieldUpdatePayload):
    id: str


class BriefTypeFormFieldRequest(BaseFormFieldRequest):
    values: NotRequired[
        list[WorkRequestTextBriefRequest | WorkRequestAttachmentBriefRequest]
    ]


class BriefTypeFormFieldResponse(BaseFormFieldResponse):
    values: NotRequired[
        list[WorkRequestTextBriefResponse | WorkRequestAttachmentBriefResponse]
    ]


class CampaignBriefResponse(TypedDict):
    fields: list[Field]
    links: Links7
    template: NotRequired[CampaignBriefTemplateValue | None]
    title: str
    type: Literal["template", "attachment", "text"]


CampaignFieldUpdateRequest: TypeAlias = (
    StringTypeObjectFieldUpdatePayload
    | MultiChoiceTypeObjectFieldUpdatePayload
    | DropdownTypeObjectFieldUpdatePayload
    | RadioButtonTypeObjectFieldUpdatePayload
    | NumberTypeObjectFieldUpdatePayload
    | DateTypeObjectFieldUpdatePayload
    | AssetTypeObjectFieldUpdatePayload
)


class CampaignResponse(TypedDict):
    budget: BudgetResponse | None
    created_at: str
    description: str | None
    end_date: str | None
    id: str
    is_hidden: bool
    labels: list[ResourceLabelResponse]
    links: Links11
    reference_id: str
    start_date: str | None
    status: Literal["Not Started", "Off Track", "On Track", "Complete", "At Risk"]
    title: str


class ContentFieldValueWithEmbeddedModel(TypedDict):
    content_details: RecursiveStructuredContent


class ContentFieldsVersionValidation(TypedDict):
    fields: NotRequired[dict[str, dict[str, ErrorReason]]]


class CoreFieldDef(TypedDict):
    editor_metadata: NotRequired[dict[str, Any] | list[Any]]
    field_type: NotRequired[FieldType]
    help_text: NotRequired[str]
    is_list: bool
    is_required: bool
    key: str
    max_list_length: NotRequired[int]
    min_list_length: NotRequired[int]
    name: str
    need_internationalization: bool
    order_index: NotRequired[int]
    source_id: NotRequired[str]
    source_metadata: NotRequired[str]


class CurrencyNumberTypeSettingsFieldCreatePayload(
    GenericNumberTypeSettingsFieldCreatePayload
):
    currency_code: NotRequired[str]


class CurrencyNumberTypeSettingsFieldResponse(GenericNumberTypeSettingsFieldResponse):
    currency_code: str


class CurrencyNumberTypeSettingsFieldUpdatePayload(
    GenericNumberTypeSettingsFieldUpdatePayload
):
    currency_code: NotRequired[str]


class DateTypeObjectField(BaseObjectField, DateTypeObjectFieldUpdatePayload):
    pass


class DatetimeFieldDefinition(TypedDict):
    core: CoreFieldDef
    default_values: NotRequired[list[str]]
    max_date: str
    min_date: str


class DropdownTypeObjectField(BaseObjectField, DropdownTypeObjectFieldUpdatePayload):
    pass


FieldListResponseItem: TypeAlias = (
    FieldTypeCommon
    | FieldTypeLabel
    | FieldTypeDropdown
    | FieldTypeRadio
    | FieldTypeCheckbox
    | FieldTypeSimpleNumber
    | FieldTypePercentageNumber
    | FieldTypeCurrencyNumber
)


class FileTypeFormFieldRequest(BaseFormFieldRequest):
    values: NotRequired[list[FileTypeFormFieldValueRequest]]


class FileTypeFormFieldResponse(BaseFormFieldResponse):
    values: NotRequired[list[FileTypeFormFieldValueResponse]]


class FolderPermissionListResponseItem(TypedDict):
    data: list[BasePermissionsResponseSchema]
    pagination: Pagination2


class FormField(TypedDict):
    custom_field_type: str | None
    field_type: str
    help: str
    identifier: str
    is_required: bool
    logic_rules: list[LogicRule]
    sort_order: int


class HTTPValidationError(TypedDict):
    detail: NotRequired[list[ValidationError]]


class LabelGroup(TypedDict):
    id: str
    name: str
    source_org_type: Literal["current", "related"]
    values: list[LabelGroupValue]


class LibraryArticle(TypedDict):
    authors: list[ArticleAuthorResponse]
    created_at: str
    expires_at: str | None
    file_location: str
    folder_id: str | None
    group_id: str | None
    html_body: str
    id: str
    images: list[FeaturedImageResponse]
    is_archived: bool
    labels: list[ResourceLabelResponse]
    lang_code: str | None
    meta_description: str | None
    meta_keywords: list[str]
    meta_title: str | None
    meta_url: str | None
    modified_at: str
    owner_id: str
    owner_organization_id: str
    pixel_key: str
    source_article: str | None
    source_name: str | None
    tags: list[Tag]
    thumbnail_url: str | None
    title: str
    url: str | None
    version_id: str
    version_number: int


class LibraryAssetDefaultValue(TypedDict):
    asset_guid: str
    asset_type: LibraryAssetType


class LibraryAssetFieldDefinition(TypedDict):
    allowed_types: list[LibraryAssetType]
    core: CoreFieldDef
    default_values: NotRequired[list[LibraryAssetDefaultValue]]


class LibraryAssetFieldValueModel(TypedDict):
    asset_guid: str
    asset_type: LibraryAssetType
    links: NotRequired[dict[str, str]]
    order_index: NotRequired[int]


class LibraryImage(TypedDict):
    allow_se_indexing: bool
    alt_text: str | None
    attribution_text: str | None
    created_at: str
    description: str | None
    expires_at: str | None
    file_extension: str | None
    file_location: str
    file_size: int
    focal_point: FocalPoint | None
    folder_id: str | None
    id: str
    image_resolution: ImageResolution
    is_archived: bool
    is_public: bool
    labels: list[ResourceLabelResponse]
    mime_type: str
    modified_at: str
    owner_id: str
    owner_organization_id: str
    tags: list[Tag]
    thumbnail_url: str | None
    title: str
    url: str
    version_id: str
    version_number: int


class LibraryImageUpdateRequest(TypedDict):
    allow_se_indexing: NotRequired[bool]
    alt_text: NotRequired[str]
    attribution_text: NotRequired[str]
    description: NotRequired[str]
    expires_at: NotRequired[str | None]
    folder_id: NotRequired[str | None]
    is_archived: NotRequired[bool]
    is_public: NotRequired[bool]
    labels: NotRequired[list[ResourceLabelRequest]]
    tags: NotRequired[list[Tag1]]
    title: NotRequired[str]


class LibraryRawFile(TypedDict):
    allow_se_indexing: bool
    attribution_text: str | None
    created_at: str
    description: str | None
    expires_at: str | None
    file_extension: str | None
    file_location: str
    file_size: int
    folder_id: str | None
    id: str
    is_archived: bool
    is_public: bool
    labels: list[ResourceLabelResponse]
    mime_type: str
    modified_at: str
    owner_id: str
    owner_organization_id: str
    tags: list[Tag]
    thumbnail_url: str | None
    title: str
    url: str
    version_id: str
    version_number: int


class LibraryRawFileUpdateRequest(TypedDict):
    allow_se_indexing: NotRequired[bool]
    attribution_text: NotRequired[str]
    description: NotRequired[str]
    expires_at: NotRequired[str | None]
    folder_id: NotRequired[str | None]
    is_archived: NotRequired[bool]
    is_public: NotRequired[bool]
    labels: NotRequired[list[ResourceLabelRequest]]
    tags: NotRequired[list[Tag1]]
    title: NotRequired[str]


class LibraryVideo(TypedDict):
    allow_se_indexing: bool
    alt_text: str | None
    attribution_text: str | None
    created_at: str
    description: str | None
    expires_at: str | None
    file_extension: str | None
    file_location: str
    file_size: int
    folder_id: str | None
    id: str
    is_archived: bool
    is_public: bool
    labels: list[ResourceLabelResponse]
    mime_type: str
    modified_at: str
    owner_id: str
    owner_organization_id: str
    tags: list[Tag]
    thumbnail_url: str | None
    title: str
    url: str
    version_id: str
    version_number: int


class LibraryVideoUpdateRequest(TypedDict):
    allow_se_indexing: NotRequired[bool]
    alt_text: NotRequired[str]
    attribution_text: NotRequired[str]
    description: NotRequired[str]
    expires_at: NotRequired[str | None]
    folder_id: NotRequired[str | None]
    is_archived: NotRequired[bool]
    is_public: NotRequired[bool]
    labels: NotRequired[list[ResourceLabelRequest]]
    tags: NotRequired[list[Tag1]]
    title: NotRequired[str]


class LocalizedFieldValuesWithEmbeddedContent(TypedDict):
    field_values: list[
        NumberFieldValueModel
        | BooleanFieldValueModel
        | DatetimeFieldValueModel
        | TextFieldValueModel
        | RichTextFieldValueModel
        | LibraryAssetFieldValueModel
        | ContentFieldValueWithEmbeddedModel
        | ContentFieldValueModel
        | URLFieldValueModel
        | JSONFieldValueModel
        | ChoiceFieldValueModel
        | LocationFieldValueModel
    ]
    locale: str


class MultiChoiceTypeObjectField(
    BaseObjectField, MultiChoiceTypeObjectFieldUpdatePayload
):
    pass


class NumberFieldDefinition(TypedDict):
    core: CoreFieldDef
    default_values: NotRequired[list[float]]
    max_value: NotRequired[float]
    min_value: NotRequired[float]


class NumberTypeObjectField(BaseObjectField, NumberTypeObjectFieldUpdatePayload):
    pass


class PublishingChannelListResponse(TypedDict):
    data: list[PublishingChannelResponse]
    pagination: Pagination2


class PublishingEventMetadataBulkCreateRequest(TypedDict):
    data: list[PublishingEventMetadataCreateRequest]


class PublishingEventMetadataBulkCreateResponse(TypedDict):
    data: list[PublishingEventMetadataResponse]
    errors: list[Error1]


class PublishingEventMetadataListResponse(TypedDict):
    data: NotRequired[list[PublishingEventMetadataResponse]]


class RadioButtonTypeObjectField(
    BaseObjectField, RadioButtonTypeObjectFieldUpdatePayload
):
    pass


class RichTextFieldDefinition(TypedDict):
    core: CoreFieldDef
    default_values: NotRequired[list[str]]
    max_visual_text_length: NotRequired[int]
    min_visual_text_length: int


SettingsFieldCreateRequest: TypeAlias = (
    BaseSettingsFieldCreatePayload
    | LabelTypeSettingsFieldCreatePayload
    | DropdownTypeSettingsFieldCreatePayload
    | CheckboxAndRadioTypeSettingsFieldCreatePayload
    | GenericNumberTypeSettingsFieldCreatePayload
    | CurrencyNumberTypeSettingsFieldCreatePayload
)


SettingsFieldUpdateRequest: TypeAlias = (
    BaseSettingsFieldUpdatePayload
    | LabelAndDropdownTypeSettingsFieldUpdatePayload
    | GenericNumberTypeSettingsFieldUpdatePayload
    | CurrencyNumberTypeSettingsFieldUpdatePayload
)


class SettingsLabelGroup(TypedDict):
    has_single_value: bool
    label_type: str
    labels: list[SettingsLabelGroupLabel]


class SettingsTemplate(TypedDict):
    description: str
    form_fields: list[FormField]
    instructions: list[Instruction]
    name: str
    public_description: str
    sections: list[Section]
    types: list[str]


class StringTypeObjectField(BaseObjectField, StringTypeObjectFieldUpdatePayload):
    pass


TaskAssetRequest: TypeAlias = (
    TaskAssetRequestForDirectUpload | TaskAssetRequestForLibrary
)


class TaskBriefResponse(TypedDict):
    fields: list[Field1]
    links: Links28
    template: NotRequired[TaskBriefTemplateValue | None]
    title: str
    type: Literal["template", "attachment", "text"]


TaskFieldUpdateRequest: TypeAlias = (
    StringTypeObjectFieldUpdatePayload
    | MultiChoiceTypeObjectFieldUpdatePayload
    | DropdownTypeObjectFieldUpdatePayload
    | RadioButtonTypeObjectFieldUpdatePayload
    | NumberTypeObjectFieldUpdatePayload
    | DateTypeObjectFieldUpdatePayload
    | AssetTypeObjectFieldUpdatePayload
)


class TaskStep(TypedDict):
    description: str | None
    due_at: str | None
    id: str
    is_completed: bool
    sub_steps: list[TaskSubStep]
    title: str


class TemplateLogicRuleItem(TypedDict):
    action: TemplateLogicRuleAction
    condition: TemplateLogicRuleCondition


TemplateLogicRule: TypeAlias = list[TemplateLogicRuleItem]


class TemplatePercentageNumberFormField(BaseTemplateFormField):
    logic_rules: TemplateLogicRule
    type_specific_meta: TypeSpecificMeta3


class TemplateSimpleNumberFormField(BaseTemplateFormField):
    logic_rules: TemplateLogicRule
    type_specific_meta: TypeSpecificMeta4


class TextFieldDefinition(TypedDict):
    core: CoreFieldDef
    default_values: NotRequired[list[str]]
    max_length: NotRequired[int]
    min_length: int
    validation_pattern: str


class Datum1(UserListResponseItem):
    links: Links39


class UserListResponse(TypedDict):
    data: list[Datum1]
    pagination: Pagination2


FormFields1: TypeAlias = (
    BriefTypeFormFieldRequest
    | DateTypeFormFieldRequest
    | FileTypeFormFieldRequest
    | MultiChoiceTypeFormFieldRequest
    | NumberTypeFormFieldRequest
    | RadioButtonTypeFormFieldRequest
    | TextTypeFormFieldRequest
)


class WorkRequestCreateRequest(TypedDict):
    assignees: NotRequired[list[str]]
    form_fields: list[FormFields1]
    template_id: str


Values: TypeAlias = WorkRequestTextBriefRequest | WorkRequestAttachmentBriefRequest


class WorkRequestRequestFormFieldBriefTypePayload(TypedDict):
    type: Literal["brief"]
    values: list[Values]


Values1: TypeAlias = WorkRequestTextBriefResponse | WorkRequestAttachmentBriefResponse


class WorkRequestRequestFormFieldBriefTypeResponse(TypedDict):
    type: Literal["brief"]
    values: list[Values1]


WorkRequestRequestFormFieldUpdateResponse: TypeAlias = (
    WorkRequestRequestFormFieldBriefTypeResponse
    | WorkRequestRequestFormFieldCheckboxTypeResponse
    | WorkRequestRequestFormFieldCurrencyNumberTypePayload
    | WorkRequestRequestFormFieldDateTypePayload
    | WorkRequestRequestFormFieldDropdownTypeResponse
    | WorkRequestRequestFormFieldFileTypeResponse
    | WorkRequestRequestFormFieldLabelTypeResponse
    | WorkRequestRequestFormFieldPercentageNumberTypePayload
    | WorkRequestRequestFormFieldRadioButtonTypeResponse
    | WorkRequestRequestFormFieldRichtextTypePayload
    | WorkRequestRequestFormFieldSimpleNumberTypePayload
    | WorkRequestRequestFormFieldTextAreaTypePayload
    | WorkRequestRequestFormFieldTextTypePayload
)


FormFields2: TypeAlias = (
    BriefTypeFormFieldResponse
    | DateTypeFormFieldResponse
    | FileTypeFormFieldResponse
    | MultiChoiceTypeFormFieldResponse
    | NumberTypeFormFieldResponse
    | RadioButtonTypeFormFieldResponse
    | TextTypeFormFieldResponse
)


class WorkRequestResponse(TypedDict):
    assignees: list[Assignee]
    created_at: str
    created_by: CreatedBy
    form_fields: list[FormFields2]
    id: str
    links: Links52
    modified_at: str
    priority: Literal["Low", "Medium", "High"]
    reference_id: str
    status: Literal["Accepted", "Declined", "Submitted", "Completed"]
    template: Template


class WorkflowStep(TypedDict):
    description: str | None
    duration: int | None
    label: str
    substeps: list[WorkflowSubStep]


class ListAssetsResponse(TypedDict):
    data: list[AssetResponse]
    pagination: Pagination2
    total_count: float


class ListCampaignFieldsResponse(TypedDict):
    data: list[FieldListResponseItem]
    pagination: Pagination2


class ListEventFieldsResponse(TypedDict):
    data: list[FieldListResponseItem]
    pagination: Pagination2


Data: TypeAlias = (
    BaseSettingsFieldsResponse
    | LabelTypeSettingsFieldResponse
    | DropdownTypeSettingsFieldResponse
    | CheckboxAndRadioTypeSettingsFieldResponse
    | GenericNumberTypeSettingsFieldResponse
    | CurrencyNumberTypeSettingsFieldResponse
)


class ListFieldsResponse(TypedDict):
    data: list[Data]
    pagination: Pagination2


class ListLabelGroupsResponse(TypedDict):
    data: list[LabelGroup]
    pagination: Pagination2


class ListTaskFieldsResponse(TypedDict):
    data: list[FieldListResponseItem]
    pagination: Pagination2


class ListWorkRequestsResponse(TypedDict):
    data: list[WorkRequestResponse]
    pagination: Pagination2


AssetFieldListResponseItem: TypeAlias = (
    AssetFieldTypeCommon
    | AssetFieldTypeLabel
    | AssetFieldTypeDropdown
    | AssetFieldTypeRadio
    | AssetFieldTypeCheckbox
    | AssetFieldTypeSimpleNumber
    | AssetFieldTypePercentageNumber
    | AssetFieldTypeCurrencyNumber
)


AssetFieldUpdateRequest: TypeAlias = (
    StringTypeObjectFieldUpdatePayload
    | MultiChoiceTypeObjectFieldUpdatePayload
    | DropdownTypeObjectFieldUpdatePayload
    | RadioButtonTypeObjectFieldUpdatePayload
    | NumberTypeObjectFieldUpdatePayload
    | DateTypeObjectFieldUpdatePayload
    | AssetTypeObjectFieldUpdatePayload
)


class AssetTypeObjectField(BaseObjectField, AssetTypeObjectFieldUpdatePayload):
    pass


class BaseFieldDefinition(TypedDict):
    base_type: BaseFieldDefinitionType
    core: CoreFieldDef
    default_values: NotRequired[
        list[LocationDefaultValue | bool | str | dict[str, Any] | list[Any]]
    ]


class ChoiceFieldDefinition(TypedDict):
    choices: dict[str, str]
    core: CoreFieldDef
    default_values: NotRequired[list[str]]
    display_option: NotRequired[ChoiceDisplayOption]


class ContentTypeFieldDefinition(TypedDict):
    allow_ref_edit: NotRequired[bool]
    allowed_content_types: list[str]
    content_type_links: NotRequired[dict[str, AllowedContentTypeItem]]
    core: CoreFieldDef
    default_value: NotRequired[str]
    ref_type: ContentTypeFieldEmbedMixConfig


Fields: TypeAlias = (
    StringTypeObjectField
    | MultiChoiceTypeObjectField
    | DropdownTypeObjectField
    | RadioButtonTypeObjectField
    | NumberTypeObjectField
    | DateTypeObjectField
    | AssetTypeObjectField
)


class EventCreateRequest(TypedDict):
    campaign_id: NotRequired[str]
    description: NotRequired[str]
    end_date: str
    fields: NotRequired[list[Fields]]
    is_all_day: bool
    start_date: str
    title: str


EventFieldsUpdateRequest1: TypeAlias = (
    MultiChoiceTypeObjectField
    | StringTypeObjectField
    | DropdownTypeObjectField
    | RadioButtonTypeObjectField
    | NumberTypeObjectField
    | DateTypeObjectField
    | AssetTypeObjectField
)


EventFieldsUpdateRequest: TypeAlias = list[EventFieldsUpdateRequest1]


ObjectFieldCreateRequest: TypeAlias = (
    StringTypeObjectField
    | MultiChoiceTypeObjectField
    | DropdownTypeObjectField
    | RadioButtonTypeObjectField
    | NumberTypeObjectField
    | DateTypeObjectField
    | AssetTypeObjectField
)


class SCContentTypeCreateRequest(TypedDict):
    created_by: str
    details: CoreContentType
    expected_locales: NotRequired[list[str]]
    field_definitions: list[
        ContentTypeFieldDefinition
        | LibraryAssetFieldDefinition
        | TextFieldDefinition
        | BaseFieldDefinition
        | DatetimeFieldDefinition
        | RichTextFieldDefinition
        | ChoiceFieldDefinition
        | NumberFieldDefinition
    ]
    source: NotRequired[str]
    source_id: NotRequired[str]
    source_metadata: NotRequired[str]


class SCContentTypeVersion(BaseContentTypeVersionModel):
    field_definitions: list[
        ContentTypeFieldDefinition
        | LibraryAssetFieldDefinition
        | TextFieldDefinition
        | BaseFieldDefinition
        | DatetimeFieldDefinition
        | RichTextFieldDefinition
        | ChoiceFieldDefinition
        | NumberFieldDefinition
    ]


class SCContentTypeVersionCreateRequest(TypedDict):
    created_by: str
    expected_locales: NotRequired[list[str]]
    field_definitions: list[
        ContentTypeFieldDefinition
        | LibraryAssetFieldDefinition
        | TextFieldDefinition
        | BaseFieldDefinition
        | DatetimeFieldDefinition
        | RichTextFieldDefinition
        | ChoiceFieldDefinition
        | NumberFieldDefinition
    ]


class SettingsWorkflow(TypedDict):
    blacklisted_channels: list[WorkflowChannel]
    custom_fields: list[WorkflowCustomfield]
    default_channels: list[WorkflowChannel]
    description: str | None
    is_flexible_workflow: bool
    is_not_pushed_to_library_by_default: bool
    is_released_as_asset: bool
    labels: list[WorkflowLabel]
    name: str
    steps: list[WorkflowStep]


TaskAssetFieldsUpdateRequest1: TypeAlias = (
    StringTypeObjectField
    | MultiChoiceTypeObjectField
    | DropdownTypeObjectField
    | RadioButtonTypeObjectField
    | NumberTypeObjectField
    | DateTypeObjectField
    | AssetTypeObjectField
)


TaskAssetFieldsUpdateRequest: TypeAlias = list[TaskAssetFieldsUpdateRequest1]


class TaskResponse(TypedDict):
    campaign_id: str | None
    due_at: str | None
    id: str
    is_archived: bool
    is_completed: bool
    labels: list[ResourceLabelResponse]
    links: Links35
    milestone_id: str | None
    modified_at: str | None
    reference_id: str
    start_at: str | None
    status: Literal[
        "Archived", "Completed", "Overdue", "Not Started", "In Progress", "On Hold"
    ]
    steps: list[TaskStep]
    title: str
    workflow_id: NotRequired[str | None]


class TemplateChoiceFormField(BaseTemplateFormField):
    logic_rules: TemplateLogicRule
    type_specific_meta: TypeSpecificMeta


class TemplateCurrencyNumberFormField(BaseTemplateFormField):
    logic_rules: TemplateLogicRule
    type_specific_meta: TypeSpecificMeta1


class TemplateDefaultFormField(BaseTemplateFormField):
    logic_rules: TemplateLogicRule
    type_specific_meta: dict[str, Any] | None


class TemplateInstructionFormField(BaseTemplateFormField):
    logic_rules: TemplateLogicRule
    type_specific_meta: TypeSpecificMeta2


FormFields: TypeAlias = (
    TemplateDefaultFormField
    | TemplateCurrencyNumberFormField
    | TemplateSimpleNumberFormField
    | TemplatePercentageNumberFormField
    | TemplateChoiceFormField
    | TemplateInstructionFormField
)


class TemplateResponse(BaseTemplateResponse):
    form_fields: list[FormFields]
    links: Links39


class VersionedContentTypeModel(TypedDict):
    component: bool
    content_type_guid: str
    created_at: str
    created_by: str
    description: NotRequired[str]
    disabled: NotRequired[bool]
    links: Links46
    name: str
    source: NotRequired[str]
    source_id: NotRequired[str]
    source_metadata: NotRequired[str]
    thumbnail_guid: NotRequired[str]
    updated_at: str
    updated_by: str
    version: SCContentTypeVersion


WorkRequestFormFieldUpdateRequest: TypeAlias = (
    WorkRequestRequestFormFieldBriefTypePayload
    | WorkRequestRequestFormFieldCheckboxTypePayload
    | WorkRequestRequestFormFieldCurrencyNumberTypePayload
    | WorkRequestRequestFormFieldDateTypePayload
    | WorkRequestRequestFormFieldDropdownTypePayload
    | WorkRequestRequestFormFieldFileTypePayload
    | WorkRequestRequestFormFieldLabelTypePayload
    | WorkRequestRequestFormFieldPercentageNumberTypePayload
    | WorkRequestRequestFormFieldRadioButtonTypePayload
    | WorkRequestRequestFormFieldRichtextTypePayload
    | WorkRequestRequestFormFieldSimpleNumberTypePayload
    | WorkRequestRequestFormFieldTextAreaTypePayload
    | WorkRequestRequestFormFieldTextTypePayload
)


class ListAssetFieldsResponse(TypedDict):
    data: list[AssetFieldListResponseItem]
    pagination: Pagination2


class UpdateAssetFieldsResponse(TypedDict):
    data: list[AssetFieldListResponseItem]
    links: Links56


class ListTaskAssetFieldsResponse(TypedDict):
    data: NotRequired[list[AssetFieldListResponseItem]]
    pagination: NotRequired[Pagination2]


AssetFieldsUpdateRequest1: TypeAlias = (
    StringTypeObjectField
    | MultiChoiceTypeObjectField
    | DropdownTypeObjectField
    | RadioButtonTypeObjectField
    | NumberTypeObjectField
    | DateTypeObjectField
    | AssetTypeObjectField
)


AssetFieldsUpdateRequest: TypeAlias = list[AssetFieldsUpdateRequest1]


class SCContentType(BaseContentTypeModel):
    latest_version: SCContentTypeVersion


class Resources(TypedDict):
    apps: list[SettingsApp]
    custom_fields: CustomFields
    labels: list[SettingsLabelGroup]
    routing_rules: list[SettingsRoutingRule]
    templates: list[SettingsTemplate]
    webhooks: list[SettingsWebhook]
    workflows: list[SettingsWorkflow]


class Settings(TypedDict):
    resources: Resources


class SettingsResources(TypedDict):
    apps: list[SettingsApp]
    custom_fields: CustomFields
    labels: list[SettingsLabelGroup]
    routing_rules: list[SettingsRoutingRule]
    templates: list[SettingsTemplate]
    webhooks: list[SettingsWebhook]
    workflows: list[SettingsWorkflow]


class Resources1(TypedDict):
    apps: list[SettingsApp]
    custom_fields: CustomFields
    labels: list[SettingsLabelGroup]
    routing_rules: list[SettingsRoutingRule]
    templates: list[SettingsTemplate]
    webhooks: list[SettingsWebhook]
    workflows: list[SettingsWorkflow]


class SettingsUpdateResponse(TypedDict):
    changeset: Changeset
    resources: Resources1


class ContentDetailsModel(TypedDict):
    content_guid: str
    content_type: NotRequired[VersionedContentTypeModel]
    content_type_guid: str
    content_type_name: str
    created_at: str
    created_by: str
    expired: NotRequired[bool]
    expiry_datetime: NotRequired[str]
    latest_fields_version: ContentFieldsVersionDetails
    links: Links12
    primary_locale: NotRequired[str]
    root_content: bool
    source: NotRequired[str]
    source_id: NotRequired[str]
    source_metadata: NotRequired[str]
    template_guid: NotRequired[str]
    title: str
    updated_at: str
    updated_by: str


class ContentFieldValueExpandedModel(TypedDict):
    content_details: ContentDetailsModel
    content_guid: str
    content_url: NotRequired[str]
    embedded: bool
    order_index: NotRequired[int]


class ContentFieldWithEmbeddedPatchValueModel(TypedDict):
    content_id: str
    patch_details: RecursivePatchStructuredContentFields


class ContentFieldsVersionDetails(TypedDict):
    content_hash: str
    created_at: str
    created_by: str
    fields: dict[str, list[LocalizedFieldValues]]
    source_id: NotRequired[str]
    source_metadata: NotRequired[str]
    validation: NotRequired[ContentFieldsVersionValidation]
    version_guid: str


class LibraryStructuredContent(TypedDict):
    content_body: NotRequired[ContentDetailsModel]
    created_at: str
    file_location: str
    folder_id: str | None
    id: str
    is_archived: bool
    labels: list[ResourceLabelResponse]
    links: Links16
    modified_at: str
    owner_organization_id: str
    title: str


class ContentBody1(TypedDict):
    expired: NotRequired[bool | None]
    expiry_datetime: NotRequired[str | None]
    fields: NotRequired[StructuredContentFields | None]
    source: NotRequired[str | None]
    source_id: NotRequired[str | None]
    source_metadata: NotRequired[str | None]
    title: NotRequired[str | None]


class LibraryStructuredContentUpdateRequest(TypedDict):
    content_body: NotRequired[ContentBody1]
    is_archived: NotRequired[bool]
    title: NotRequired[str | None]


class LocalizedFieldValues(TypedDict):
    field_values: list[
        NumberFieldValueModel
        | BooleanFieldValueModel
        | DatetimeFieldValueModel
        | TextFieldValueModel
        | RichTextFieldValueModel
        | LibraryAssetFieldValueModel
        | ContentFieldValueExpandedModel
        | ContentFieldValueModel
        | URLFieldValueModel
        | JSONFieldValueModel
        | ChoiceFieldValueModel
        | LocationFieldValueModel
    ]
    locale: str


class PatchLocalizedFieldValuesWithEmbeddedContent(TypedDict):
    field_values: list[
        NumberFieldValueModel
        | BooleanFieldValueModel
        | DatetimeFieldValueModel
        | TextFieldValueModel
        | RichTextFieldValueModel
        | LibraryAssetFieldValueModel
        | ContentFieldValueWithEmbeddedModel
        | ContentFieldValueModel
        | URLFieldValueModel
        | JSONFieldValueModel
        | ChoiceFieldValueModel
        | LocationFieldValueModel
        | DeleteFieldValueModel
        | ContentFieldWithEmbeddedPatchValueModel
    ]
    locale: str


class RecursivePatchStructuredContentFields(TypedDict):
    content_body: NotRequired[StructuredContentFields]
    expired: NotRequired[bool]
    expiry_datetime: NotRequired[str | None]
    root_content: NotRequired[bool]
    source: NotRequired[str | None]
    source_id: NotRequired[str | None]
    source_metadata: NotRequired[str]
    title: NotRequired[str]


class SCContentMigrationCreateRequest(TypedDict):
    created_by: str
    fields: NotRequired[dict[str, list[LocalizedFieldValues]]]
    new_content_type_version_id: NotRequired[str]
    source: NotRequired[str | None]
    source_id: NotRequired[str | None]


class SCContentTypeManagedMigrationCreateRequest(TypedDict):
    created_by: str
    default_values: NotRequired[LocalizedFieldValues]
    source_content_type_version_id: str


class SCContentTypeManagedMigrationValidateRequest(TypedDict):
    default_values: NotRequired[LocalizedFieldValues]
    source_content_type_version_id: str


StructuredContentFields: TypeAlias = dict[
    str,
    list[PatchLocalizedFieldValuesWithEmbeddedContent | DeleteLocaleFieldValueModel],
]


class TaskStructuredContentDraftRequest(TypedDict):
    content_body: LocalizedFieldValues


class TaskStructuredContentUpdateRequest(TypedDict):
    expired: NotRequired[bool]
    expiry_datetime: NotRequired[str | None]
    fields: NotRequired[StructuredContentFields]
    primary_locale: NotRequired[str]
    source: NotRequired[str | None]
    source_id: NotRequired[str | None]
    source_metadata: NotRequired[str | None]
    title: NotRequired[str]


__all__ = [
    "AddUrlToTaskRequest",
    "ArticleAuthorResponse",
    "AssetFieldListResponseItem",
    "AssetFieldUpdateRequest",
    "AssetFieldUpdateResponse",
    "AssetFieldsUpdateRequest",
    "AssetLineageCreateRequest",
    "AssetLineageResponse",
    "AssetPermissionBulkCreateRequest",
    "AssetPermissionListResponseItem",
    "AssetPermissionUpdateRequest",
    "AssetResponse",
    "AssetTypeObjectFieldUpdatePayload",
    "AssetVersionCreateRequest",
    "AttachmentRequest",
    "AttachmentResponse",
    "BaseAssetRenditionResponse",
    "BaseFormFieldRequest",
    "BaseFormFieldResponse",
    "BaseObjectFieldUpdatePayload",
    "BaseSettingsFieldCreatePayload",
    "BaseSettingsFieldUpdatePayload",
    "BaseSettingsFieldsResponse",
    "BaseTemplateResponse",
    "BatchFileUrlResponse",
    "BrandComplianceCategoriesResponse",
    "BriefTypeFormFieldRequest",
    "BriefTypeFormFieldResponse",
    "BudgetResponse",
    "CampaignBriefResponse",
    "CampaignCommentResponse",
    "CampaignCreateRequest",
    "CampaignFieldUpdateRequest",
    "CampaignFieldUpdateResponse",
    "CampaignListResponseItem",
    "CampaignResponse",
    "CampaignUpdateRequest",
    "CheckboxAndRadioTypeSettingsFieldCreatePayload",
    "CheckboxAndRadioTypeSettingsFieldResponse",
    "CommentCreateRequest",
    "CommentWithReplyCreateRequest",
    "CompleteMultipartUploadResponse",
    "CreateFieldResponse",
    "CreateMultipartUploadResponse",
    "CreateSCContentTypeManagedMigrationResponse",
    "CreateTaskStructuredContentDraftResponse",
    "CreativeAssetRequest",
    "CreativeAssetResponse",
    "CurrencyNumberTypeSettingsFieldCreatePayload",
    "CurrencyNumberTypeSettingsFieldResponse",
    "CurrencyNumberTypeSettingsFieldUpdatePayload",
    "DateTypeFormFieldRequest",
    "DateTypeFormFieldResponse",
    "DateTypeObjectFieldUpdatePayload",
    "DetailedAssetRenditionResponse",
    "DropdownTypeObjectFieldUpdatePayload",
    "DropdownTypeSettingsFieldCreatePayload",
    "DropdownTypeSettingsFieldResponse",
    "EventCreateRequest",
    "EventFieldsUpdateRequest",
    "EventResponse",
    "EventUpdateRequest",
    "FeaturedImageResponse",
    "FieldListResponseItem",
    "FileTypeFormFieldRequest",
    "FileTypeFormFieldResponse",
    "FileTypeFormFieldValueRequest",
    "FileTypeFormFieldValueResponse",
    "FileUrlBulkCreateRequest",
    "FolderCreateRequest",
    "FolderPermissionBulkCreateRequest",
    "FolderPermissionListResponseItem",
    "FolderPermissionUpdateRequest",
    "FolderResponse",
    "FolderUpdateRequest",
    "GenericNumberTypeSettingsFieldCreatePayload",
    "GenericNumberTypeSettingsFieldResponse",
    "GenericNumberTypeSettingsFieldUpdatePayload",
    "GenericSettingsFieldChoiceCreatePayload",
    "GenericSettingsFieldChoiceUpdatePayload",
    "GetMultipartUploadStatusResponse",
    "GetUploadUrlResponse",
    "LabelAndDropdownTypeSettingsFieldUpdatePayload",
    "LabelTypeSettingsFieldChoiceCreatePayload",
    "LabelTypeSettingsFieldChoiceUpdatePayload",
    "LabelTypeSettingsFieldCreatePayload",
    "LabelTypeSettingsFieldResponse",
    "LibraryAssetCreateRequest",
    "LibraryAssetVersionResponse",
    "LibraryImageUpdateRequest",
    "LibraryRawFileUpdateRequest",
    "LibraryStructuredContentCreateRequest",
    "LibraryStructuredContentUpdateRequest",
    "LibraryVideoUpdateRequest",
    "ListAssetFieldsResponse",
    "ListAssetLineagesResponse",
    "ListAssetRenditionsResponse",
    "ListAssetsResponse",
    "ListBrandComplianceCategoriesResponse",
    "ListCampaignFieldsResponse",
    "ListCampaignsResponse",
    "ListEventFieldsResponse",
    "ListEventsResponse",
    "ListFieldsResponse",
    "ListFoldersResponse",
    "ListLabelGroupsResponse",
    "ListMilestonesResponse",
    "ListSCContentTypeManagedMigrationsResponse",
    "ListSCContentTypeVersionsResponse",
    "ListSCContentTypesResponse",
    "ListTaskAssetCommentsResponse",
    "ListTaskAssetDraftsResponse",
    "ListTaskAssetFieldsResponse",
    "ListTaskAssetsResponse",
    "ListTaskAttachmentsResponse",
    "ListTaskCustomFieldChoicesResponse",
    "ListTaskCustomFieldsResponse",
    "ListTaskFieldsResponse",
    "ListTaskSubStepCommentsResponse",
    "ListTaskSubStepFieldsResponse",
    "ListTasksResponse",
    "ListTeamsResponse",
    "ListWorkRequestApprovedAssetsResponse",
    "ListWorkRequestCommentsResponse",
    "ListWorkRequestRelatedResourcesResponse",
    "ListWorkRequestsResponse",
    "ListWorkflowsResponse",
    "MigrateSCContentResponse",
    "MilestoneCreateRequest",
    "MilestoneResponse",
    "MilestoneUpdateRequest",
    "MultiChoiceTypeFormFieldRequest",
    "MultiChoiceTypeFormFieldResponse",
    "MultiChoiceTypeObjectFieldUpdatePayload",
    "NumberTypeFormFieldRequest",
    "NumberTypeFormFieldResponse",
    "NumberTypeObjectFieldUpdatePayload",
    "ObjectFieldCreateRequest",
    "ObjectFieldCreateResponse",
    "PublishingChannelListResponse",
    "PublishingChannelResponse",
    "PublishingEventMetadataBulkCreateRequest",
    "PublishingEventMetadataBulkCreateResponse",
    "PublishingEventMetadataCreateRequest",
    "PublishingEventMetadataListResponse",
    "PublishingEventMetadataResponse",
    "PublishingEventResponse",
    "RadioButtonTypeFormFieldRequest",
    "RadioButtonTypeFormFieldResponse",
    "RadioButtonTypeObjectFieldUpdatePayload",
    "RelatedAssetsListResponse",
    "RenditionConfigResponse",
    "ReplaceRelatedAssetsRequest",
    "ReplaceRelatedAssetsResponse",
    "ResourceChoiceResponse",
    "ResourceLabelRequest",
    "ResourceLabelResponse",
    "SCContentMigrationCreateRequest",
    "SCContentPreviewAcknowledgeRequest",
    "SCContentPreviewCompleteRequest",
    "SCContentTypeCreateRequest",
    "SCContentTypeCreateResponse",
    "SCContentTypeManagedMigrationCreateRequest",
    "SCContentTypeManagedMigrationResponse",
    "SCContentTypeManagedMigrationStartResponse",
    "SCContentTypeManagedMigrationValidateRequest",
    "SCContentTypeUpdateRequest",
    "SCContentTypeUpdateResponse",
    "SCContentTypeVersionCreateRequest",
    "SettingsFieldChoiceCreateRequest",
    "SettingsFieldChoiceCreateResponse",
    "SettingsFieldChoiceUpdateRequest",
    "SettingsFieldCreateRequest",
    "SettingsFieldUpdateRequest",
    "SettingsUpdateResponse",
    "StringTypeObjectFieldUpdatePayload",
    "TaskAssetCommentResponse",
    "TaskAssetDraftBrandComplianceRequest",
    "TaskAssetDraftBrandComplianceResponse",
    "TaskAssetDraftListResponseItem",
    "TaskAssetDraftResponse",
    "TaskAssetFieldsUpdateRequest",
    "TaskAssetRequest",
    "TaskAssetResponse",
    "TaskBriefResponse",
    "TaskCommentResponse",
    "TaskCreateRequest",
    "TaskCustomFieldChoiceListResponseItem",
    "TaskCustomFieldUpdateRequest",
    "TaskExternalWorkRequest",
    "TaskExternalWorkResponse",
    "TaskFieldUpdateRequest",
    "TaskListResponseItem",
    "TaskPublishingIntentCreateRequest",
    "TaskPublishingIntentResponse",
    "TaskResponse",
    "TaskStepRequest",
    "TaskStructuredContentCreateRequest",
    "TaskStructuredContentDraftRequest",
    "TaskStructuredContentUpdateRequest",
    "TaskSubStepCommentResponse",
    "TaskSubStepCommentUpdateRequest",
    "TaskSubStepRequest",
    "TaskUpdateRequest",
    "TaskUrlResponse",
    "TemplateListResponse",
    "TemplateResponse",
    "TextTypeFormFieldRequest",
    "TextTypeFormFieldResponse",
    "UpdateAssetFieldsResponse",
    "UpdateSCContentTypeManagedMigrationResponse",
    "UserListResponse",
    "UserListResponseItem",
    "UserResponse",
    "ValidateSCContentTypeManagedMigrationResponse",
    "WorkRequestApprovedAssetResponse",
    "WorkRequestAttachmentBriefRequest",
    "WorkRequestAttachmentBriefResponse",
    "WorkRequestCampaignRequest",
    "WorkRequestCampaignResponse",
    "WorkRequestCommentResponse",
    "WorkRequestCreateRequest",
    "WorkRequestFormFieldUpdateRequest",
    "WorkRequestRelatedResourceResponse",
    "WorkRequestRequestFormFieldBriefTypePayload",
    "WorkRequestRequestFormFieldBriefTypeResponse",
    "WorkRequestRequestFormFieldCheckboxTypePayload",
    "WorkRequestRequestFormFieldCheckboxTypeResponse",
    "WorkRequestRequestFormFieldCurrencyNumberTypePayload",
    "WorkRequestRequestFormFieldDateTypePayload",
    "WorkRequestRequestFormFieldDropdownTypePayload",
    "WorkRequestRequestFormFieldDropdownTypeResponse",
    "WorkRequestRequestFormFieldFileTypePayload",
    "WorkRequestRequestFormFieldFileTypeResponse",
    "WorkRequestRequestFormFieldLabelTypePayload",
    "WorkRequestRequestFormFieldLabelTypeResponse",
    "WorkRequestRequestFormFieldPercentageNumberTypePayload",
    "WorkRequestRequestFormFieldRadioButtonTypePayload",
    "WorkRequestRequestFormFieldRadioButtonTypeResponse",
    "WorkRequestRequestFormFieldRichtextTypePayload",
    "WorkRequestRequestFormFieldSimpleNumberTypePayload",
    "WorkRequestRequestFormFieldTextAreaTypePayload",
    "WorkRequestRequestFormFieldTextTypePayload",
    "WorkRequestRequestFormFieldUpdateResponse",
    "WorkRequestResponse",
    "WorkRequestTaskRequest",
    "WorkRequestTaskResponse",
    "WorkRequestTextBriefRequest",
    "WorkRequestTextBriefResponse",
    "WorkRequestUpdateRequest",
    "WorkflowListResponseItem",
    "WorkflowResponse",
]
